### ISSUE TITLE
Error `Couldn't find any result for id <n> while Generating constraints for <args>` produced by out of order operators

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1002]
Minimal repro:

```
// t.qnt
module t {
  def a() = b()
  def b() = 1
}
```

```
$  quint typecheck t.qnt 
...
Error: Couldn't find any result for id 4 while Generating constraints for b()
    at TypeInferrer.fetchResult (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/types/constraintGenerator.js:204:19)
    at TypeInferrer.typeForName (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/types/constraintGenerator.js:243:25)
    ... 
```

This will be fixed indirectly by @konnov's work on topologically sorting defs, but it still maybe indicates we're not producing or handling these errors optimally:

1. Id error shouldn't be given to the user.
2. Users should never see stack traces.

This was reported by @angbrav and @rnbguy.

**Comment by konnov** [comment]
Fixed via #1008. Now the type checker is reporting the following error, which I think is expected:

```bluespec
t2.qnt:2:13 - error: [QNT000] Couldn't unify int and oper
Trying to unify int and () => t0

2:   def a() = b()
               ^^^

/Users/igor/devl/informal/quint/quint/t2.qnt:2:13 - error: [QNT000] Can't unify different types of effects
Trying to unify Pure and () => e0
Trying to infer effect for operator application in b()

2:   def a() = b()
```
