### ISSUE TITLE
Error reporter fails during test 

### ISSUE THREAD

**Issue by angbrav** [informalsystems/quint#1061]
When running `quint test` on [this spec](https://github.com/informalsystems/partnership-heliax/tree/manuel/quint-report-issue/2023/Q2/artifacts/PoS-quint), a test fails and the error reporter crashes.

Quint version: 0.12.0

The quint test command:
`quint test --main=namada --max-samples=10 --match=slashValidatorTest --verbosity=3 namada-redelegation.qnt`

The error:
```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at formatLine (/opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/errorReporter.js:64:19)
    at /opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/errorReporter.js:50:23
    at Array.reduce (<anonymous>)
    at formatError (/opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/errorReporter.js:34:25)
    at /opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/cliCommands.js:272:65
    at Array.forEach (<anonymous>)
    at runTests (/opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/cliCommands.js:271:25)
    at EitherConstructor.asyncChain (/opt/homebrew/lib/node_modules/@informalsystems/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
    at /opt/homebrew/lib/node_modules/@informalsystems/quint/dist/src/cli.js:33:39
```

Line 64 of errorReporter.js: `output += '^'.repeat(1 + endCol - startCol);`

**Comment by konnov** [comment]
Thank you for the detailed bug report @angbrav. It does reproduce on v0.12.0. For some reason, it works on main. We will add extra catches to make sure that error reporting does not error itself
