### ISSUE TITLE
Crashing when lambda is used as value

### ISSUE THREAD

**Issue by bugarela** [informalsystems/quint#1192]
We don't allow lambdas to be used as values, but we should provide a proper error instead of crashing. Here's one example:

```
module A {
  pure val foo = Set(1).map(i => (x => x + 1))
}
```

which crashes with:

```
quint typecheck <input>

check types and effects of a Quint specification

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --out      output file (suppresses all console output)                [string]

TypeError: Cannot read properties of undefined (reading 'freshVarGenerator')
    at /home/gabriela/projects/quint/quint/dist/src/effects/inferrer.js:288:88
    at Array.map (<anonymous>)
    at newInstance (/home/gabriela/projects/quint/quint/dist/src/effects/inferrer.js:287:56)
    at EitherConstructor.map (/home/gabriela/projects/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:75:40)
    at EffectInferrer.exitLambda (/home/gabriela/projects/quint/quint/dist/src/effects/inferrer.js:223:14)
    at walkExpression (/home/gabriela/projects/quint/quint/dist/src/ir/IRVisitor.js:348:25)
    at /home/gabriela/projects/quint/quint/dist/src/ir/IRVisitor.js:336:38
    at Array.forEach (<anonymous>)
    at walkExpression (/home/gabriela/projects/quint/quint/dist/src/ir/IRVisitor.js:336:23)
    at walkDefinition (/home/gabriela/projects/quint/quint/dist/src/ir/IRVisitor.js:279:13)
```

**Comment by shonfeder** [comment]
A proper fix of this should also fix #456 iiuc, since the root cause this is also that we are not ensuring operator don't appear as values during type checking.

**Comment by konnov** [comment]
This bug is similar to #1212, though they are a bit different

**Comment by p-offtermatt** [comment]
This code fragment also caused the issue (observe there is no return value, since after the val there is nothing):

```
m.dst.flatten().forall(
                receiver => 
                    // get messages tagged with S1 sent by p relating to m
                    val sentMessages = networkState.get((p, receiver)).exists(
                        msg => msg.id == m.id and
                            msg.tag == "S1"
                    )
            ),
```
