### ISSUE TITLE
Uncaught exception when `quint verify`  is interrupted with ctr-c

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#1197]
To reproduce, run

```
quint verify  --main prisoners3 --random-transitions --invariant safetyInv,countInv examples/puzzles/prisoners/prisoners.qnt 
```

And then ctrl-c after giving it a few seconds to produce

```
Error: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.run (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at Object.<anonymous> (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:179:55)
    at node:internal/util:377:7
    at new Promise (<anonymous>)
    at Object.run (node:internal/util:363:12)
    at Object.check (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:96:44)
    at /home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:341:53
    at EitherConstructor.asyncChain (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
    at verify (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/quintVerifier.js:341:29) {
  code: 1,
  details: 'Call cancelled',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

**Comment by bugarela** [comment]
Doesn't happen anymore, probably fixed by https://github.com/informalsystems/quint/pull/1729
