### ISSUE TITLE
Error in error reporting by the type checker

### ISSUE THREAD

**Issue by p-offtermatt** [informalsystems/quint#1199]
This is my spec:
https://github.com/cosmos/interchain-security/blob/289ccad3c7d8fc3cd1fbaa9b5116c7737af42414/tests/difference/core/quint_model/

I am running this command:

```
quint run --invariant "all{CanRunConsumer,CanStopConsumer,CanTimeoutConsumer,CanSendVSCPackets,CanSendVSCMaturedPackets}" ccv_statemachine.qnt --main CCVDefaultStateMachine --max-steps 2000 --max-samples 200
```

I get this output:

```
Something unexpected happened during error reconstruction. Please report a bug.

Include this in the bug report: {
Trace: Invalid count value: -22
    at formatError (/Users/offtermatt/projects/quint/quint/dist/src/errorReporter.js:62:17)
    at /Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:581:81
    at Array.forEach (<anonymous>)
    at /Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:581:20
    at EitherConstructor.mapLeft (/Users/offtermatt/projects/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:67:43)
    at outputResult (/Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:573:10)
} // end of the bug report

error: [QNT000] Couldn't unify rec and tup
Trying to unify { chainState: ChainState, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] } and (Chain, { chainState: { currentValidatorSet: ValidatorSet, votingPowerHistory: VotingPowerHistory, lastTimestamp: Time }, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] })
Trying to unify { providerState: { consumerStatus: (Chain -> str), chainState: { lastTimestamp: int, votingPowerHistory: VotingPowerHistory, currentValidatorSet: ValidatorSet }, outstandingPacketsToConsumer: (Chain -> List[VSCPacket]), receivedMaturations: Set[VSCMaturedPacket], sentVSCPackets: (Chain -> List[VSCPacket]), providerValidatorSetChangedInThisBlock: bool, runningVscId: int }, consumerStates: (Chain -> ConsumerState) } and { consumerStates: (Chain -> (Chain, { chainState: { currentValidatorSet: ValidatorSet, votingPowerHistory: VotingPowerHistory, lastTimestamp: Time }, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] })) | tail_t1326 }


Something unexpected happened during error reconstruction. Please report a bug.

Include this in the bug report: {
Trace: Invalid count value: -22
    at formatError (/Users/offtermatt/projects/quint/quint/dist/src/errorReporter.js:62:17)
    at /Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:581:81
    at Array.forEach (<anonymous>)
    at /Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:581:20
    at EitherConstructor.mapLeft (/Users/offtermatt/projects/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:67:43)
    at outputResult (/Users/offtermatt/projects/quint/quint/dist/src/cliCommands.js:573:10)
} // end of the bug report

error: [QNT000] Couldn't unify rec and tup
Trying to unify { chainState: ChainState, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] } and (Chain, { chainState: { currentValidatorSet: ValidatorSet, votingPowerHistory: VotingPowerHistory, lastTimestamp: Time }, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] })
Trying to unify { providerState: { consumerStatus: (Chain -> str), chainState: { lastTimestamp: int, votingPowerHistory: VotingPowerHistory, currentValidatorSet: ValidatorSet }, outstandingPacketsToConsumer: (Chain -> List[VSCPacket]), receivedMaturations: Set[VSCMaturedPacket], sentVSCPackets: (Chain -> List[VSCPacket]), providerValidatorSetChangedInThisBlock: bool, runningVscId: int }, consumerStates: (Chain -> ConsumerState) } and { consumerStates: (Chain -> (Chain, { chainState: { currentValidatorSet: ValidatorSet, votingPowerHistory: VotingPowerHistory, lastTimestamp: Time }, maturationTimes: (VSCPacket -> Time), receivedVSCPackets: List[VSCPacket], outstandingPacketsToProvider: List[VSCMaturedPacket] })) | tail_t1326 }

error: typechecking failed
```

My version of Quint is 0.14.3

**Comment by p-offtermatt** [comment]
If it helps, the error in my spec is the tuple return here:
https://github.com/cosmos/interchain-security/blob/289ccad3c7d8fc3cd1fbaa9b5116c7737af42414/tests/difference/core/quint_model/ccv.qnt#L460 and here https://github.com/cosmos/interchain-security/blob/289ccad3c7d8fc3cd1fbaa9b5116c7737af42414/tests/difference/core/quint_model/ccv.qnt#L462
where the first part of the pair needs to be dropped

**Comment by konnov** [comment]
This looks like an error in error reporting by the type checker

**Comment by bugarela** [comment]
Found the problem! This a direct consequence of https://github.com/informalsystems/quint/issues/1174. We are trying to report an error in the `ccv_statemachine.qnt` file while the actual error is in `ccv.qnt`. In this case, the line for the error (464) doesn't even exist on the `ccv_statemachine.qnt` file, so error reporting breaks. Fixing the other issue should solve this one as well.

Thanks for reporting!
