### ISSUE TITLE
Internal error while flattening [QNT404] Name 'Listed' not found

### ISSUE THREAD

**Issue by eras** [informalsystems/quint#1418]
Trying to verify the accompanying model results in error 

```
Error: Internal error while flattening [QNT404] Name 'Listed' not found
    at resolveNamesOrThrow (/home/user/.npm-packages/lib/node_modules/@informalsystems/quint/dist/src/flattening/fullFlattener.js:91:15)
    at flattenModules (/home/user/.npm-packages/lib/node_modules/@informalsystems/quint/dist/src/flattening/fullFlattener.js:62:35)
    at compile (/home/user/.npm-packages/lib/node_modules/@informalsystems/quint/dist/src/cliCommands.js:493:104)
    at EitherConstructor.asyncChain (/home/user/.npm-packages/lib/node_modules/@informalsystems/quint/node_modules/@sweet-monads/either/cjs/index.js:125:16)
    at /home/user/.npm-packages/lib/node_modules/@informalsystems/quint/dist/src/cli.js:58:39
```

Steps to reproduc:
1) Install `quint` version 0.19.1
1) Save the following to `Simple.qnt`:
```
module T {
  type State =
    | Listed

  type File = {
    state : State,
  }

  def listed(files: int -> File) : Set[int] =
    files.keys().filter(x => files.get(x).state == Listed)
}

module Spec {
  import T.*

  const init_files: int -> File

  var files: int -> File

  action init = all {
    files' = init_files
  }

  action step = {
    nondet file_id = oneOf(listed(files))
    files' = files
  }
}

module Simple {
  import T.*
  pure val file1: File = {
    state  : Listed,
  }
  import Spec(init_files = Map(1->file1)).*
}
```
2) `quint verify Simple.qnt`
3) Witness the error

Expected results:
- No error; possibly an explanation what I might be doing incorrectly, though it _feels_ correct to me..

It works if I move the definition `listed` to module `Spec`. It also works if I incorporate the `Simple` module inside `Spec`.

**Comment by bugarela** [comment]
Hi, thanks for reporting! Seems it might be related to the error I've hit in https://github.com/informalsystems/quint/issues/1353.

Unfortunately, Quint's flattening (which converts multiple modules into a single one) is probably our most unstable feature, specially in the presence of constants and instances. I'm glad you found a workaround!
