### ISSUE TITLE
Uncaught assertion error when parsing defined union type

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#213]
Given this module 

```scala
module ClockSync3 {
// control states
type state = 
  | {tag : "init"}
  | {tag : "sent"}
  | {tag : "sync"}
}
```

calling `tntnc parse` yields the following uncaught exception:

```
AssertionError [ERR_ASSERTION]: popTypes: too few elements in typeStack
    at ToIrListener.popTypes (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/ToIrListener.js:870:29)
    at ToIrListener.exitTypeUnionRec (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/ToIrListener.js:750:38)
    at TypeUnionRecContext.exitRule (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/generated/TntParser.js:3244:22)
    at ParseTreeWalker.exitRule (/home/sf/Sync/informal-systems/apalache/tnt/tntc/node_modules/antlr4ts/tree/ParseTreeWalker.js:94:13)
    at ParseTreeWalker.walk (/home/sf/Sync/informal-systems/apalache/tnt/tntc/node_modules/antlr4ts/tree/ParseTreeWalker.js:52:26)
    at parsePhase1 (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/tntParserFrontend.js:80:51)
    at parseText (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/cli.js:92:62)
    at parseModule (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/cli.js:87:12)
    at Object.parse [as handler] (/home/sf/Sync/informal-systems/apalache/tnt/tntc/dist/src/cli.js:37:5)
    at /home/sf/Sync/informal-systems/apalache/tnt/tntc/node_modules/yargs/build/index.cjs:1:9052 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

Adding additional fields to the records seems to avert the crash:

```
type state = 
  | {tag : "init", v : int}
  | {tag : "sent", m : int}
  | {tag : "sync", l : int}
```

**Comment by shonfeder** [comment]
We've removed unions
