### ISSUE TITLE
Uncaught exception in repl when trying to apply defined operator in map

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/quint#681]
```
$  quint
Quint REPL v0.0.3
Type ".exit" to exit, or ".help" for more information
>>> val f = (x, y) => x + y

>>> Set(Tup(1, 2)).map(f)
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.strict)(callable.registers.length === 1)

    at CompilerVisitor.mapLambdaThenReduce (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/runtime/impl/compilerImpl.js:678:29)
    at CompilerVisitor.exitApp (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/runtime/impl/compilerImpl.js:499:22)
    at walkExpression (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/IRVisitor.js:288:25)
    at walkDefinition (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/IRVisitor.js:206:13)
    at /home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/IRVisitor.js:232:44
    at Array.forEach (<anonymous>)
    at walkDefinition (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/IRVisitor.js:232:29)
    at walkModule (/home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/IRVisitor.js:54:5)
    at /home/sf/Sync/informal-systems/apalache/quint/quint/dist/src/runtime/compile.js:66:36
    at EitherConstructor.chain (/home/sf/Sync/informal-systems/apalache/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:108:16) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v19.6.0
```

**Comment by shonfeder** [comment]
Maybe related to #365

but we should still ensure we don't crash on unsupported expressions in the REPL.

**Comment by konnov** [comment]
Yeah, I think it is related to #365.

**Comment by konnov** [comment]
This is working now. Closing the issue.

```bluespec
$ quint 
Quint REPL 0.9.1
Type ".exit" to exit, or ".help" for more information
>>> val f = (x, y) => x + y

>>> Set(Tup(1, 2)).map(f)
Set(3)
>>> 

```
