### ISSUE TITLE
REPL throws on naming conflict

### ISSUE THREAD

**Issue by thpani** [informalsystems/quint#863]
I encountered this when copy-pasting from a spec:

When I copy-paste the following `val` declaration, REPL throws and exits with

```
~/s/quint/examples/cosmos/ics20 ❯❯❯ quint -r ics20.qnt::ics20Test
Quint REPL 0.10.0
Type ".exit" to exit, or ".help" for more information
true

>>> val chainState = chainStates.get("A")
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

Error: Error on resolving names for flattened modules: Conflicting definitions found for name chainState in module __repl__
    at /Users/thomas/src/quint/quint/dist/src/runtime/compile.js:106:19
    at EitherConstructor.mapLeft (/Users/thomas/src/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:56:43)
    at /Users/thomas/src/quint/quint/dist/src/runtime/compile.js:102:14
    at Array.map (<anonymous>)
    at compile (/Users/thomas/src/quint/quint/dist/src/runtime/compile.js:94:38)
    at /Users/thomas/src/quint/quint/dist/src/runtime/compile.js:169:21
    at EitherConstructor.chain (/Users/thomas/src/quint/quint/node_modules/@sweet-monads/either/cjs/index.js:108:16)
    at compileFromCode (/Users/thomas/src/quint/quint/dist/src/runtime/compile.js:164:10)
    at tryEval (/Users/thomas/src/quint/quint/dist/src/repl.js:537:55)
    at nextLine (/Users/thomas/src/quint/quint/dist/src/repl.js:139:39)
```

**Comment by konnov** [comment]
The comment says it should not happen, as name resolution should have found that. @bugarela, ideas? Anyway, we should not throw an exception there, but show an internal error or something.

**Comment by bugarela** [comment]
It's a duplicate from https://github.com/informalsystems/quint/issues/802
@konnov we talked about starting to support shadowing and you said you wanted to think about it. Any new thoughts?

**Comment by bugarela** [comment]
This was fixed by the new flattener
