### ISSUE TITLE
Wrong version of Node.js

### ISSUE THREAD

**Issue by otrack** [informalsystems/quint#867]
The [installation](https://github.com/otrack/quint/blob/pierre/mempool/quint/README.md) mentions that Node.js >= 14 is required. However, it is in fact Node.js >= 15.

Using node v14.21.2 (on Ubuntu 20.04), in the [second lesson](https://github.com/informalsystems/quint/blob/main/tutorials/lesson2-integers/integers.md), we hit the following problem with exponentiation:
 
```
>  echo "2^2" | quint
TypeError: intNode.text.replaceAll is not a function
    at ToIrListener.exitLiteralOrId (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/ToIrListener.js:358:44)
    at LiteralOrIdContext.exitRule (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/generated/QuintParser.js:5146:22)
    at ParseTreeWalker.exitRule (/home/otrack/ALL/myWork/Implementation/quint/quint/node_modules/antlr4ts/tree/ParseTreeWalker.js:94:13)
    at ParseTreeWalker.walk (/home/otrack/ALL/myWork/Implementation/quint/quint/node_modules/antlr4ts/tree/ParseTreeWalker.js:52:26)
    at parsePhase1fromText (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/quintParserFrontend.js:97:51)
    at compileFromCode (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/runtime/compile.js:154:58)
    at tryEval (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/repl.js:474:55)
    at nextLine (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/repl.js:139:39)
    at Interface.<anonymous> (/home/otrack/ALL/myWork/Implementation/quint/quint/dist/src/repl.js:191:13)
    at Interface.emit (events.js:400:28)
```

Upgrading Node.js fixes this.

**Comment by shonfeder** [comment]
I've needed to pick up a later version of node for #871, and also reasoned we should use the active LTS branch. So i have this in the works as a side effect. :)
