### ISSUE TITLE
`verify` fails on `BinSearch10.qnt`

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#936]
Using the example in #935. I do the following:

In tab 1:

```sh
$ cd $APALACHE_HOME
$ apalache-mc server --write-intermediate=true
```

In tab 2:

```
$ export APALACHE_DIST=$APALACHE_HOME/target/universal/apalache-0.40.3-SNAPSHOT/
$ cd $QUINT_HOME/examples/classic/sequential/BinSearch
$ quint verify --init=Init --step=Next --invariant=Postcondition BinSearch10.qnt
```

This is what I see in tab 1:

```
Error: internal error: unhandled verification error at pass SanyParser
    at handleVerificationFailure (/Users/igor/devl/informal/quint/quint/dist/src/quintVerifier.js:66:19)
    at Object.check (/Users/igor/devl/informal/quint/quint/dist/src/quintVerifier.js:83:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

This is what I see in tab 2:

```
  > Error parsing file StringSource(Qnt)                          E@09:37:46.988
  > Input was not a valid representation of the QuintIR: Definition has invalid `kind` field: LinkedHashMap(id -> 17, kind -> "instance", qualifiedName -> "I", protoName -> "BinSearch", overrides -> [[{"id":14,"name":"INPUT_SEQ"},{"id":11,"kind":"app","opcode":"List","args":[{"id":1,"kind":"int","value":1},{"id":2,"kind":"int","value":2},{"id":3,"kind":"int","value":3},{"id":4,"kind":"int","value":4},{"id":5,"kind":"int","value":5},{"id":6,"kind":"int","value":6},{"id":7,"kind":"int","value":8},{"id":8,"kind":"int","value":9},{"id":9,"kind":"int","value":10},{"id":10,"kind":"int","value":33}]}],[{"id":15,"name":"INPUT_KEY"},{"id":12,"kind":"int","value":7}],[{"id":16,"name":"INT_WIDTH"},{"id":13,"kind":"int","value":16}]], identityOverride -> false, fromSource -> "./BinSearch") E@09:37:46.989
```

**Comment by shonfeder** [comment]
I suspect this is due to not yet having support for `instance`s.
